name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Cypress run
      uses: cypress-io/github-actions@v2
      with:
        buid: npm run build
        start: npm start

   
